---
all:
  hosts:
    sonar-01:
      ansible_host: 89.169.146.8
      ansible_ssh_user: centos
      ansible_ssh_private_key_file: /home/barmaq/.ssh/ycbarmaq.rsa
      #ansible_python_interpreter: /usr/bin/python3
    nexus-01:
      ansible_host: 89.169.150.121
      ansible_ssh_user: centos
      ansible_ssh_private_key_file: /home/barmaq/.ssh/ycbarmaq.rsa
      #ansible_python_interpreter: /usr/bin/python3
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: <someuser>